### ISSUE TITLE
Print the death message on login if player died whilst AFK

### ISSUE THREAD

**Issue by James103** [samolego/AntiLogout#1]
If a player dies whilst being AFK (logged-in server side, either with `/afk` or by disconnecting shortly after being attacked) and then that player logs in, no death message is displayed as shown in the video even though the player did die.

This means a player could log in after death and not know the cause of said death, especially if the time span between death and login was very long (minutes or even hours).

By contrast, if a player goes AFK but remains truly connected for the same time frame, and the player dies during that time, the death message will remain on the death screen, in chat, and in the client logs.

**Comment by samolego** [comment]
I guess I could save the death message and show it on client screen.
Putting it in chat again might not be the best option, since it's already printed when player dies (while afk).

**Comment by James103** [comment]
> Putting it in chat again might not be the best option

There is a way to display chat messages to a specific player only, allowing only the connecting player to get the death message in chat again instead of everyone on the server.

**Comment by samolego** [comment]
Ah, that's right
